version: "3"
services:
  web_backend:
    image:  nginx:latest
    ports:
      - "80"
    networks:
      - mynet
    deploy:
      replicas: 2
  web_fronted:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  mynet: